print ('welcometo deloid')
print ('Enter your name:')
name=input()
print('Enter your mobile number:')
mno=input()
print('Enter your Email address:')
email=input()
print('Enter the password:')
pwd=input()
print('Re-enter the password:')
rpwd=input()
print('welcome '+name)
print('you are in')
print('Any further queries use '+email+' as your email and use '+pwd+' as your password')
